### ISSUE TITLE
Replace hard coded value in function w/ parameter

### ISSUE THREAD

**Issue by gregthompson27** [AveryJade1/AveryJade1.github.io#3]
https://github.com/AveryJade1/AveryJade1.github.io/blob/027304e6e6a9a35ef14e6ea299b6f5fc07fc0be7/projects/bouncing-box/index.html#L51-L53

@AveryJade1, looks like you replaced the parameter that was being used on line 52 with the value `500`. So this function is hardcoded to set the box's CSS to be 500 pixels from the left of the screen. Go ahead and replace the `500` with the `newPositionX` parameter, and your box should start moving again.

___

https://github.com/AveryJade1/AveryJade1.github.io/blob/027304e6e6a9a35ef14e6ea299b6f5fc07fc0be7/projects/bouncing-box/index.html#L78

Also, go ahead and delete this call to the `update` function that you added on line 78, and right click and "Format Document" while you're at it!

**Comment by JoshHunter11** [comment]
@gregthompson27 Update function removed. Regarding the issue with the moveBoxTo function, the student did change their parameter and their box does move in the program as intended, but the parameter is just positionX as opposed to newPositionX, though it does look like the code works fine.
